name: movie_case
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.4.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  number_pagination: ^1.1.6
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.0
  flutter_inner_shadow: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/photos/

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 100
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/photos/SinFlixLogo.png"

flutter_native_splash:
  color: "#ffffff" # Arkaplan rengi
  image: assets/photos/SinFlixSplash.png # Göstermek istediğin görsel
  android: true
  ios: true
  web: false